id: 'a93d0953-ebd5-45d0-eae0-08dbfa1c9dae'
version: 'v1.1'
name: 'Manuel_002'
description: 'asf'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.2.0'
sourceSystems:
  - id: '96ba554f-bc27-4b49-b097-2484804560ac'
    name: 'ERP'
    description: ''
  - id: '44ed6185-60ff-4132-89fa-61cc40387e16'
    name: 'POS'
    description: ''
  - id: '6af52770-a9cb-4d3e-ad41-5a3910ddf6ab'
    name: 'bfm'
    description: ''
