views:
  - id: '8d564ccf-8724-49ae-92f9-140dace349f8'
    name: 'Datapipe View 1'
    description: 'Default view for data pipe.'
    type: 'data-pipe'
    default: true
    modelObjects:
      - id: '5b899aae-4b39-4ccd-a951-354a7d98f91d'
      - id: 'd08b47d0-f5f2-4604-8d62-b0dcff899a8e'
      - id: '377f2162-a2db-4522-8614-2505cf0a0659'
      - id: 'e3cefc0e-43c9-4111-95ad-e7cbe30b1b00'
      - id: '56822f2b-16b1-41bd-b309-b188fbf7753d'
      - id: '0f991102-1918-422e-9b8c-3d824e326cb3'
  - id: '69d73ad3-1596-4cb6-ad9c-df73764e0a0e'
    name: 'Datamodel View 1'
    description: 'Default view for data model.'
    type: 'data-model'
    default: true
    modelObjects: []
